### PR TITLE
fix: use taobao to detect ip && fallback with .npmrc

### PR DESCRIPTION
**Pull request by atian25**
close https://github.com/eggjs/egg-init/pull/8

### CODE REVIEW

**Comment by fengmk2** [comment]
这是 fix，不是 feat。改一下就合并发布。

**Comment by shaoshuai0102** [comment]
This will be used only when egg-init is executing, right?

If true, LGTM.

If not, custom registry should be used, because people use their own private registries.

**Comment by atian25** [comment]
@fengmk2 done.

@shaoshuai0102 yes,  just use this to check & download boilerplate,  will not affect the generated project.

**Comment by atian25** [comment]
1.2.1

**Pull request merged**
